### PR TITLE
add three fields with {fhr} in ncl_name

### PR DESCRIPTION
**Pull request by cshartsough**
Added acpcp, acfrzr, and weasd.  All were fields with {fhr} in the ncl_name.

Plots to follow...

### CODE REVIEW

**Comment by cshartsough** [comment]
Plots.  snow and snow water are empty but color tables are set.  we should think about the height contours on the precip plot.

[Web graphics - PR 50.pptx](https://github.com/NOAA-GSD/adb_graphics/files/5144170/Web.graphics.-.PR.50.pptx)

**Comment by Brian-Jamison** [comment]
Good job on these.  We definitely don't want height contours, but rather MSLP and thickness contours on the precip plots.
Other than that, everything looks great!

**Comment by christinaholtNOAA** [comment]
Looks good!

**Comment by Brian-Jamison** [comment]
Technically, it should read, "remove MSLP overlay from total precip"

Looks good!

**Pull request merged**
