### PR TITLE
Adding GitHub Actions workflow

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
My first attempt at adding a GitHub Actions workflow. 

This puts two grib files from HRRR in the repo using git-lfs. The tests are our standard set -- linting and pytest suite. I also updated the environment.yml to match our pygraf environment instead of the older verison of adb_grpaphics. 

I have no idea if this will work!

### CODE REVIEW

**Comment by christinaholtNOAA** [comment]
There's a good chance that I need to merge this PR before the actions can be tested.... :(

**Review by cshartsough — APPROVED** [review]
Lots in here that's still over my head, but the parts I could see and work through look good.

**Comment by Brian-Jamison** [comment]
I echo Craig's sentiments.

**Review by Brian-Jamison — APPROVED** [review]
Looks good!

**Pull request merged**
